Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "docker"
  config.vm.network 'private_network', ip: "172.16.11.100"
   config.vm.provider 'virtualbox' do |vb|
     vb.memory = 2048
     vb.cpus = 1
   end
end
